class TodoJsonKeys:
    MONDAY = "monday"
    TUESDAY = "tuesday"
    WEDNESDAY = "wednesday"
    THURSDAY = "thursday"
    FRIDAY = "friday"
    SATURDAY = "saturday"
    SUNDAY = "SUNDAY"
    TASKS = "tasks"
    TASK = "task"
    ESTIMATE_TIME = "estimate_time"
    START = "start"
    END = "end"
    STATUS = "status"

